name: CI/CD Pipeline (fixed)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    # run steps from the repository root (do not set a nested working-directory)

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: 'pip'
        # dependency file path should be relative to the repository root
        cache-dependency-path: requirements.txt

    - name: Install dependencies
      run: |
        echo "=== Installing dependencies ==="
        pwd
        ls -la
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        echo "Dependencies installed successfully"

    - name: Run tests
      run: |
        echo "=== Running tests ==="
        pwd
        ls -la tests/
        python -m pytest tests/ -v --tb=short

    - name: Run ML pipeline
      run: |
        echo "=== Running ML pipeline ==="
        pwd
        ls -la
        python main.py

    - name: Check model performance
      run: |
        echo "=== Checking model performance ==="
        pwd
        ls -la reports/
        python .github/scripts/check_model_performance.py

    - name: Prepare artifacts
      run: |
        echo "=== Preparing artifacts ==="
        pwd
        ls -la models/ reports/

    - name: Upload model artifacts
      uses: actions/upload-artifact@v4
      with:
        name: model-artifacts
        path: |
          models/
          reports/
        if-no-files-found: error
        retention-days: 30
